sudo: false

language: node_js

notifications:
  email: false

node_js:
- stable

cache:
  directories:
  - node_modules

script:
- npm run lint
- npm run flow
- npm run build
- npm run test:acceptance
- npm run test:coverage

after_success:
- npm run codecov
- npm run release

branches:
  only:
  - master
