sudo: false

language: node_js

notifications:
  email: false

node_js:
- 8

cache:
  directories:
  - node_modules

before_script:
- npm prune

script:
- npm run lint
- npm run flow
- npm run test:coverage
- npm run test:acceptance

after_success:
- npm run codecov
- npm run release

branches:
  only:
  - master
  - /^greenkeeper/.*$/
